if [ -f "/etc/bash_completion" ] ; then
    . "/etc/bash_completion"
fi

export PATH="/workspace/src/vendor/bin:~/.local/bin:$PATH"
export PATH="/workspace/src/node_modules/.bin:$PATH"

source "$HOME/.aliases"
source "$HOME/.autocomplete"

export PROMPT_COMMAND='history -a'

export EDITOR=vim

if command -v starship &> /dev/null; then
    eval "$(starship init bash)"
fi
