x-php-environment: &php-environment
  APP_ENV:
  APP_SECRET:
  DATABASE_URL: ${DB_ENGINE:-sqlsrv}://sa:${DB_PASSWORD:-!ChangeMe123!}@${DB_HOST:-database}:${DB_PORT:-1433}/${DB_DATABASE:-dinamis}?serverVersion=${DB_VERSION:-2022}&charset=UTF-8
x-php-buildargs: &php-buildargs
  APP_ENV:
  DEBIAN_APT_MIRROR:
  PHP_VERSION: 8.2
  TIMEZONE: Asia/Jakarta
services:
  workspace:
    build:
      dockerfile: src/Dockerfile
      context: ./
      args:
        INSTALL_BASH_COMPLETION: true
        INSTALL_LESS: ${WORKSPACE_INSTALL_LESS:-false}
        INSTALL_NETCAT: ${WORKSPACE_INSTALL_NETCAT:-false}
        INSTALL_NODEJS: current
        INSTALL_OPENSSH_CLIENT: ${WORKSPACE_INSTALL_OPENSSH_CLIENT:-false}
        INSTALL_SUDO: true
        INSTALL_SYMFONY_CLI: ${WORKSPACE_INSTALL_SYMFONY_CLI:-false}
        INSTALL_VIM: true
        INSTALL_XDEBUG: ${WORKSPACE_INSTALL_XDEBUG:-false}
    user: ${UID:-1000}
    command: >
      bash -c '
        echo "Setting file permissions";
        sudo mkdir -p /workspace/.data/workspace/cache;
        sudo mkdir -p /workspace/.data/workspace/local;
        sudo mkdir -p /workspace/.data/workspace/vscode-server;
        sudo usermod -a $(id -nu ${UID:-1000}) -G www-data
        sudo chown -R ${UID:-1000}:${GID:-1000} /workspace/.data/workspace;
        sudo chown -R ${UID:-1000}:www-data /workspace/src/var;
        sudo chown -R www-data:www-data /workspace/src/uploads;
        sudo chown -R 10001:10001 /var/opt/mssql;
        sudo find /workspace/src/var -type d -exec chmod 775 {} +;
        sudo find /workspace/src/var -type f -exec chmod 664 {} +;

        echo "Creating softlink";
        ln -sf /workspace/.workspace/autocomplete ~/.autocomplete;
        ln -sf /workspace/.workspace/aliases ~/.aliases;
        ln -sf /workspace/.workspace/bashrc ~/.bashrc;
        ln -sf /workspace/.data/workspace/cache ~/.cache;
        ln -sf /workspace/.data/workspace/local ~/.local;
        ln -sf /workspace/.data/workspace/vscode-server ~/.vscode-server;


        if [[ ! -f ~/.local/bash_history ]]; then
          touch ~/.local/bash_history;
        fi;
        ln -sf ~/.local/bash_history ~/.bash_history;

        echo "Installing starship";
        mkdir -p ~/.local/bin;
        mkdir -p ~/.config;
        curl -sS https://starship.rs/install.sh | sh -s -- -b ~/.local/bin --yes >/dev/null 2>&1;
        ln -sf /workspace/.workspace/config/starship.toml ~/.config/starship.toml;

        echo "Installing dependency";
        if command -v npm &> /dev/null; then
            npm config set prefix '~/.local';
            npm config set cache '~/.cache';
            npm install -g npm
        fi

        cd /workspace/app && composer install;

        echo "All done!";
        while sleep 1000; do :; done
      '
    environment:
      <<: *php-environment
      EDITOR:
      XDEBUG_MODE:
    volumes:
      - ./.data/mssql:/var/opt/mssql/data:Z
      - ./:/workspace:cached
      - ${SSH_HOST_DIR:-./.workspace/ssh}:${SSH_REMOTE_DIR:-/home/sipandai/.ssh}
  app:
    image: nginx:stable-alpine
    depends_on:
      - php-fpm
    ports:
      - '${PORT_PREFIX:-81}81:80'
    volumes:
      - ./src/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/
  php-fpm:
    build:
      dockerfile: src/Dockerfile
      context: ./
      args:
        <<: *php-buildargs
        PHP_VARIANT: fpm
    environment:
      <<: *php-environment
    volumes:
      - ./:/var/www
    working_dir: /var/www/app
  php-worker:
    build:
      dockerfile: src/Dockerfile
      context: ./
      args:
        <<: *php-buildargs
        INSTALL_SUPERVISOR: true
    command: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
    environment:
      <<: *php-environment
    ports:
      - '127.0.0.1:${PORT_PREFIX:-81}83:9001'
    volumes:
      - .workspace/supervisord.conf:/etc/supervisor/supervisord.conf
      - ./:/var/www
    working_dir: /var/www/app
  ui:
    image: node:20.5-alpine
    command: sh -c 'npm install && npm run watch'
    volumes:
      - ./app:/app:cached
    working_dir: /app