<?php

namespace Database\Seeders\MonitoringPimpinan\Monitoring;

use App\Models\Master\Jabatan;
use App\Models\MonitoringPimpinan\Monitoring\Action;
use App\Models\MonitoringPimpinan\Monitoring\SubjectDetail;
use Illuminate\Database\Seeder;

class ActionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $actions = [
            // SUBJECT DETAIL KE 1
            // =====================
            [
                'name'              => 'Batasan unregistered Pihak Pelapor',
                'comment'           => 'Menetapkan batasan unregistered Pihak Pelapor beserta monitoring populasi.',
                'success_indicator' => 'Pengawasan Pihak Pelapor yang Tepat Sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'REKAN')->first()->id,
            ],
            [
                'name'              => 'Audit kepatuhan tematik atau audit khusus',
                'comment'           => 'Melaksanakan audit kepatuhan tematik atau audit khusus yang massive dan sistemik.',
                'success_indicator' => 'Pengawasan Pihak Pelapor yang Tepat Sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PENJAGA')->first()->id,
            ],
            [
                'name'              => 'Audit kepatuhan tematik atau audit khusus',
                'comment'           => 'Melaksanakan audit kepatuhan tematik atau audit khusus yang massive dan sistemik.',
                'success_indicator' => 'Pengawasan Pihak Pelapor yang Tepat Sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PATUH')->first()->id,
            ],
            [
                'name'              => 'LPP menindaklanjuti rekomendasi PPATK',
                'comment'           => 'Mengharuskan LPP untuk menindaklanjuti rekomendasi PPATK terkait pengenaan sanksi dan pencabutan izin usaha.',
                'success_indicator' => 'Pengawasan Pihak Pelapor yang Tepat Sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PENJAGA')->first()->id,
            ],
            [
                'name'              => 'LPP menindaklanjuti rekomendasi PPATK',
                'comment'           => 'Mengharuskan LPP untuk menindaklanjuti rekomendasi PPATK terkait pengenaan sanksi dan pencabutan izin usaha.',
                'success_indicator' => 'Pengawasan Pihak Pelapor yang Tepat Sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PATUH')->first()->id,
            ],
            [
                'name'              => 'Mengenakan sanksi yang memiliki efek jera bagi pihak pelapor unregistered dan unreporting',
                'comment'           => 'Mengenakan sanksi yang memiliki efek jera bagi pihak pelapor unregistered dan unreporting.',
                'success_indicator' => 'Pengawasan Pihak Pelapor yang Tepat Sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PENJAGA')->first()->id,
            ],
            [
                'name'              => 'Mengenakan sanksi yang memiliki efek jera bagi pihak pelapor unregistered dan unreporting',
                'comment'           => 'Mengenakan sanksi yang memiliki efek jera bagi pihak pelapor unregistered dan unreporting.',
                'success_indicator' => 'Pengawasan Pihak Pelapor yang Tepat Sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PATUH')->first()->id,
            ],
            [
                'name'              => 'Mengembangkan sistem pengawasan pelaporan dan kepatuhan',
                'comment'           => 'Mengembangkan sistem pendukung pengawasan pelaporan dan kepatuhan.',
                'success_indicator' => 'Pengawasan Pihak Pelapor yang Tepat Sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'LOGIS')->first()->id,
            ],
            [
                'name'              => 'Mengembangkan sistem pengawasan pelaporan dan kepatuhan',
                'comment'           => 'Mengembangkan sistem pendukung pengawasan pelaporan dan kepatuhan.',
                'success_indicator' => 'Pengawasan Pihak Pelapor yang Tepat Sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'REKAN')->first()->id,
            ],
            [
                'name'              => 'Mengembangkan sistem pengawasan pelaporan dan kepatuhan',
                'comment'           => 'Mengembangkan sistem pendukung pengawasan pelaporan dan kepatuhan.',
                'success_indicator' => 'Pengawasan Pihak Pelapor yang Tepat Sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PENJAGA')->first()->id,
            ],
            [
                'name'              => 'Mengembangkan sistem pengawasan pelaporan dan kepatuhan',
                'comment'           => 'Mengembangkan sistem pendukung pengawasan pelaporan dan kepatuhan.',
                'success_indicator' => 'Pengawasan Pihak Pelapor yang Tepat Sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PATUH')->first()->id,
            ],
            [
                'name'              => 'Mengenakan sanksi yang memiliki efek jera bagi pihak pelapor yang menyampaikan laporan tidak berkualitas',
                'comment'           => 'Mengenakan sanksi yang memiliki efek jera bagi pihak pelapor yang menyampaikan laporan tidak berkualitas.',
                'success_indicator' => 'Laporan berkualitas yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PENJAGA')->first()->id,
            ],
            [
                'name'              => 'Mengenakan sanksi yang memiliki efek jera bagi pihak pelapor yang menyampaikan laporan tidak berkualitas',
                'comment'           => 'Mengenakan sanksi yang memiliki efek jera bagi pihak pelapor yang menyampaikan laporan tidak berkualitas.',
                'success_indicator' => 'Laporan berkualitas yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PATUH')->first()->id,
            ],
            [
                'name'              => 'Melaksanakan asistensi dan bimtek yang tepat sasaran',
                'comment'           => 'Melaksanakan asistensi dan bimtek yang tepat sasaran (baik objek maupun materinya).',
                'success_indicator' => 'Laporan berkualitas yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PENJAGA')->first()->id,
            ],
            [
                'name'              => 'Melaksanakan asistensi dan bimtek yang tepat sasaran',
                'comment'           => 'Melaksanakan asistensi dan bimtek yang tepat sasaran (baik objek maupun materinya).',
                'success_indicator' => 'Laporan berkualitas yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PATUH')->first()->id,
            ],
            [
                'name'              => 'Segera menetapkan 35 RPerPPATK/RSE',
                'comment'           => 'Segera menetapkan 35 RPerPPATK/RSE mengenai pelaporan.',
                'success_indicator' => 'Laporan berkualitas yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'KREASI')->first()->id,
            ],
            [
                'name'              => 'Penguatan fungsi FIR',
                'comment'           => 'Penguatan fungsi FIR sebagai Rapor Pihak Pelapor.',
                'success_indicator' => 'Laporan berkualitas yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'REKAN')->first()->id,
            ],
            [
                'name'              => 'Penguatan fungsi FIR',
                'comment'           => 'Penguatan fungsi FIR sebagai Rapor Pihak Pelapor.',
                'success_indicator' => 'Laporan berkualitas yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PENJAGA')->first()->id,
            ],
            [
                'name'              => 'Penguatan fungsi FIR',
                'comment'           => 'Penguatan fungsi FIR sebagai Rapor Pihak Pelapor.',
                'success_indicator' => 'Laporan berkualitas yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PATUH')->first()->id,
            ],
            [
                'name'              => 'Membangun aplikasi “Identifikasi Pelaporan yang Berkualitas dan Tidak Berkualitas”',
                'comment'           => 'Membangun aplikasi “Identifikasi Pelaporan yang Berkualitas dan Tidak Berkualitas”',
                'success_indicator' => 'Laporan berkualitas yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'LOGIS')->first()->id,
            ],
            [
                'name'              => 'Membangun aplikasi “Identifikasi Pelaporan yang Berkualitas dan Tidak Berkualitas”',
                'comment'           => 'Pengembangan aplikasi “Identifikasi Pelaporan yang Berkualitas dan Tidak Berkualitas”',
                'success_indicator' => 'Laporan berkualitas yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'REKAN')->first()->id,
            ],

            // SUBJECT DETAIL KE 2
            // =====================
            [
                'name'              => 'Melaksanakan prioritas inquiry',
                'comment'           => 'Melaksanakan prioritas inquiry dengan melakukan pemetaan terhadap inquiry yang belum ditindaklanjuti.',
                'success_indicator' => 'Pola kerja yang memanfaatkan seluruh basis data PPATK',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terlaksananya pola kerja baru')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SIASAT')->first()->id,
            ],
            [
                'name'              => 'Melaksanakan prioritas inquiry',
                'comment'           => 'Melaksanakan prioritas inquiry dengan melakukan pemetaan terhadap inquiry yang belum ditindaklanjuti.',
                'success_indicator' => 'Pola kerja yang memanfaatkan seluruh basis data PPATK',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terlaksananya pola kerja baru')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SIAGA')->first()->id,
            ],
            [
                'name'              => 'Melaksanakan scoring LTKM di goAML',
                'comment'           => 'Melaksanakan scoring LTKM di goAML.',
                'success_indicator' => 'Pola kerja yang memanfaatkan seluruh basis data PPATK',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terlaksananya pola kerja baru')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'LOGIS')->first()->id,
            ],
            [
                'name'              => 'Ditempatkannya pegawai yang memiliki kompetensi sebagai ahli data mining atau data scientist',
                'comment'           => 'Ditempatkannya pegawai yang memiliki kompetensi sebagai ahli data mining atau data scientist pada ASA.',
                'success_indicator' => 'Pola kerja yang memanfaatkan seluruh basis data PPATK',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terlaksananya pola kerja baru')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BERMAKNA')->first()->id,
            ],
            [
                'name'              => 'Restrukturisasi fungsi ASA 1 dan ASA 2',
                'comment'           => 'Restrukturisasi fungsi ASA 1 dan ASA 2.',
                'success_indicator' => 'Pola kerja yang memanfaatkan seluruh basis data PPATK',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terlaksananya pola kerja baru')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BERMAKNA')->first()->id,
            ],
            [
                'name'              => 'Ditempatkannya pegawai yang memiliki kompetensi analisis strategis pada ASA',
                'comment'           => 'Penempatan pegawai yang memiliki kompetensi analisis strategis pada ASA.',
                'success_indicator' => 'Pola kerja yang memanfaatkan seluruh basis data PPATK',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terlaksananya pola kerja baru')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BERMAKNA')->first()->id,
            ],
            [
                'name'              => 'Membentuk Tim Kerja Implementasi Aplikasi Go AML',
                'comment'           => 'Membentuk Tim Kerja Implementasi Aplikasi Go AML.',
                'success_indicator' => 'Sistem informasi yang andal',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terlaksananya pola kerja baru')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'LOGIS')->first()->id,
            ],
            [
                'name'              => 'Implementasi scoring LTKM proaktif di goAML',
                'comment'           => 'Implementasi scoring LTKM proaktif di goAML.',
                'success_indicator' => 'Sistem informasi yang andal',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terlaksananya pola kerja baru')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'LOGIS')->first()->id,
            ],
            [
                'name'              => 'Memperbaiki tampilan field transaction info secara lengkap',
                'comment'           => 'Memperbaiki tampilan field transaction info secara lengkap.',
                'success_indicator' => 'Sistem informasi yang andal',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terlaksananya pola kerja baru')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'LOGIS')->first()->id,
            ],
            [
                'name'              => 'Melakukan finetuning atas konfigurasi perangkat lunak database oleh expert',
                'comment'           => 'Melakukan finetuning atas konfigurasi perangkat lunak database oleh expert.',
                'success_indicator' => 'Sistem informasi yang andal',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terlaksananya pola kerja baru')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'LOGIS')->first()->id,
            ],
            [
                'name'              => 'Otomatisasi scoring prioritas inquiry di goAML',
                'comment'           => 'Otomatisasi scoring prioritas inquiry di goAML.',
                'success_indicator' => 'Sistem informasi yang andal',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terlaksananya pola kerja baru')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'LOGIS')->first()->id,
            ],
            [
                'name'              => 'Otomatisasi proses profiling PEA di goAML',
                'comment'           => 'Otomatisasi proses profiling PEA di goAML.',
                'success_indicator' => 'Sistem informasi yang andal',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terlaksananya pola kerja baru')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'LOGIS')->first()->id,
            ],
            [
                'name'              => 'Menyediakan fitur untuk menghapus data pelaporan',
                'comment'           => 'Menyediakan fitur untuk menghapus data pelaporan yang sudah terkonfirmasi salah dan melakukan rekonsiliasi data dampak atas penghapusan data pelaporan.',
                'success_indicator' => 'Sistem informasi yang andal',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terlaksananya pola kerja baru')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'LOGIS')->first()->id,
            ],
            [
                'name'              => 'Menyediakan fitur penanda (flagging) laporan',
                'comment'           => 'Menyediakan fitur penanda (flagging) laporan yang sudah dilakukan data mining tanpa menjalankan workflow goAML.',
                'success_indicator' => 'Sistem informasi yang andal',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terlaksananya pola kerja baru')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'LOGIS')->first()->id,
            ],

            // SUBJECT DETAIL KE 3
            // =====================
            [
                'name'              => 'Melakukan perubahan bobot penilaian prioritas inquiry',
                'comment'           => 'Melakukan perubahan bobot penilaian prioritas inquiry (amandemen Peraturan PPATK Nomor 10 tahun 2023).',
                'success_indicator' => 'Feedback tindak lanjut atas 100% HA/HP/INF PPATK yang berkelanjutan',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'KREASI')->first()->id,
            ],
            [
                'name'              => 'Implementasi pemenuhan inqury berdasarkan bobot penilaian prioritas inquiry',
                'comment'           => 'Implementasi pemenuhan inqury berdasarkan bobot penilaian prioritas inquiry.',
                'success_indicator' => 'Feedback tindak lanjut atas 100% HA/HP/INF PPATK yang berkelanjutan',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SIAGA')->first()->id,
            ],
            [
                'name'              => 'Memastikan tindak lanjut pemetaan HA/HP berjalan secara efektif',
                'comment'           => 'Memastikan tindak lanjut pemetaan HA/HP berjalan secara efektif.',
                'success_indicator' => 'Feedback tindak lanjut atas 100% HA/HP/INF PPATK yang berkelanjutan',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SALAM')->first()->id,
            ],
            [
                'name'              => 'Mempercepat interconnectivity SISPEKA',
                'comment'           => 'Mempercepat interconnectivity SISPEKA dengan instansi penerima.',
                'success_indicator' => 'Feedback tindak lanjut atas 100% HA/HP/INF PPATK yang berkelanjutan',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'REKAN')->first()->id,
            ],
            [
                'name'              => 'Mempercepat interconnectivity SISPEKA',
                'comment'           => 'Mempercepat interconnectivity SISPEKA dengan instansi penerima.',
                'success_indicator' => 'Feedback tindak lanjut atas 100% HA/HP/INF PPATK yang berkelanjutan',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SALAM')->first()->id,
            ],
            [
                'name'              => 'Mempercepat interconnectivity SISPEKA',
                'comment'           => 'Mempercepat interconnectivity SISPEKA dengan instansi penerima.',
                'success_indicator' => 'Feedback tindak lanjut atas 100% HA/HP/INF PPATK yang berkelanjutan',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'LOGIS')->first()->id,
            ],
            [
                'name'              => 'Melakukan penyampaian informasi khusus kepada BPK RI',
                'comment'           => 'Melakukan penyampaian informasi khusus kepada BPK RI untuk oversight pemanfaatan HA/HP/INF PPATK.',
                'success_indicator' => 'Memanfaatkan peran BPK RI dan Komite TPPU',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SIASAT')->first()->id,
            ],
            [
                'name'              => 'Melakukan penyampaian informasi khusus kepada BPK RI',
                'comment'           => 'Melakukan penyampaian informasi khusus kepada BPK RI untuk oversight pemanfaatan HA/HP/INF PPATK.',
                'success_indicator' => 'Memanfaatkan peran BPK RI dan Komite TPPU',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SIDIK')->first()->id,
            ],
            [
                'name'              => 'Tim kerja Komite TPPU segera melakukan pembahasan secara berkelanjutan mengenai rendahnya jumlah pemanfaatan HA/HP/INF',
                'comment'           => 'Tim kerja Komite TPPU segera melakukan pembahasan secara berkelanjutan mengenai rendahnya jumlah pemanfaatan HA/HP/INF dan menyepakati solusi.',
                'success_indicator' => 'Memanfaatkan peran BPK RI dan Komite TPPU',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SALAM')->first()->id,
            ],
            [
                'name'              => 'Melaksanakan Forum Tim Pelaksana dan Tim Kerja Komite TPPU Dalam Penanganan Kasus Yang Berasal dari HA/HP/INF PPATK',
                'comment'           => 'Melaksanakan Forum Tim Pelaksana dan Tim Kerja Komite TPPU Dalam Penanganan Kasus Yang Berasal dari HA/HP/INF PPATK Yang Sistemik secara berkala.',
                'success_indicator' => 'Komitmen penanganan HA/HP/INF PPATK yang sistemik',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SALAM')->first()->id,
            ],
            [
                'name'              => 'Melaksanakan Forum Tim Pelaksana dan Tim Kerja Komite TPPU Dalam Penanganan Kasus Yang Berasal dari HA/HP/INF PPATK',
                'comment'           => 'Melaksanakan Forum Tim Pelaksana dan Tim Kerja Komite TPPU Dalam Penanganan Kasus Yang Berasal dari HA/HP/INF PPATK Yang Sistemik secara berkala.',
                'success_indicator' => 'Komitmen penanganan HA/HP/INF PPATK yang sistemik',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SIASAT')->first()->id,
            ],
            [
                'name'              => 'Melaksanakan Forum Tim Pelaksana dan Tim Kerja Komite TPPU Dalam Penanganan Kasus Yang Berasal dari HA/HP/INF PPATK',
                'comment'           => 'Melaksanakan Forum Tim Pelaksana dan Tim Kerja Komite TPPU Dalam Penanganan Kasus Yang Berasal dari HA/HP/INF PPATK Yang Sistemik secara berkala.',
                'success_indicator' => 'Komitmen penanganan HA/HP/INF PPATK yang sistemik',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SIDIK')->first()->id,
            ],
            [
                'name'              => 'Melakukan validasi atas kualitas laporan capaian rencana aksi Strategi Nasional TPPU dan TPPT',
                'comment'           => 'Melakukan validasi atas kualitas laporan capaian rencana aksi Strategi Nasional TPPU dan TPPT.',
                'success_indicator' => 'Komitmen penanganan HA/HP/INF PPATK yang sistemik',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SALAM')->first()->id,
            ],
            [
                'name'              => 'Menetapkan dan melaksanakan hasil pemetaan kebutuhan kerjasama domestik dan internasional yang mendukung core ppatk',
                'comment'           => 'Menetapkan dan melaksanakan hasil pemetaan kebutuhan kerjasama domestik dan internasional yang mendukung core ppatk.',
                'success_indicator' => 'Kerja sama domestik dan internasional yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SALAM')->first()->id,
            ],
            [
                'name'              => 'Menetapkan dan melaksanakan hasil pemetaan kebutuhan kerjasama domestik dan internasional yang mendukung core ppatk',
                'comment'           => 'Menetapkan dan melaksanakan hasil pemetaan kebutuhan kerjasama domestik dan internasional yang mendukung core ppatk.',
                'success_indicator' => 'Kerja sama domestik dan internasional yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SERASI')->first()->id,
            ],
            [
                'name'              => 'Melakukan evaluasi kerja sama domestik dan internasional dan ditindaklanjuti dengan pengakhiran atau perpanjangan Nota Kesepahaman',
                'comment'           => 'Melakukan evaluasi kerja sama domestik dan internasional dan ditindaklanjuti dengan pengakhiran atau perpanjangan Nota Kesepahaman.',
                'success_indicator' => 'Kerja sama domestik dan internasional yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SALAM')->first()->id,
            ],
            [
                'name'              => 'Melakukan evaluasi kerja sama domestik dan internasional dan ditindaklanjuti dengan pengakhiran atau perpanjangan Nota Kesepahaman',
                'comment'           => 'Melakukan evaluasi kerja sama domestik dan internasional dan ditindaklanjuti dengan pengakhiran atau perpanjangan Nota Kesepahaman.',
                'success_indicator' => 'Kerja sama domestik dan internasional yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SERASI')->first()->id,
            ],
            [
                'name'              => 'Membangun dan melaksanakan kerja sama yang tepat sasaran dan berdaya guna',
                'comment'           => 'Membangun dan melaksanakan kerja sama yang tepat sasaran dan berdaya guna.',
                'success_indicator' => 'Kerja sama domestik dan internasional yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SALAM')->first()->id,
            ],
            [
                'name'              => 'Membangun dan melaksanakan kerja sama yang tepat sasaran dan berdaya guna',
                'comment'           => 'Membangun dan melaksanakan kerja sama yang tepat sasaran dan berdaya guna.',
                'success_indicator' => 'Kerja sama domestik dan internasional yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SERASI')->first()->id,
            ],
            [
                'name'              => 'Melakukan case work meeting dengan FIU negara lain',
                'comment'           => 'Melakukan case work meeting dengan FIU negara lain.',
                'success_indicator' => 'Kerja sama domestik dan internasional yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SERASI')->first()->id,
            ],
        ];

        foreach ($actions as $action) {
            Action::create([
                'name'              => $action['name'],
                'comment'           => $action['comment'],
                'success_indicator' => $action['success_indicator'],
                'start'             => $action['start'],
                'end'               => $action['end'],
                'subject_detail_id' => $action['subject_detail_id'],
                'jabatan_id'        => $action['jabatan_id'],
            ]);
        }
    }
}
