<?php

namespace Database\Seeders\MonitoringPimpinan\Monitoring;

use App\Models\Master\Jabatan;
use App\Models\MonitoringPimpinan\Monitoring\Action;
use App\Models\MonitoringPimpinan\Monitoring\SubjectDetail;
use Illuminate\Database\Seeder;

class ActionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $actions = [
            // SUBJECT DETAIL KE 1
            // =====================
            [
                'name'              => 'Batasan unregistered Pihak Pelapor',
                'comment'           => 'Menetapkan batasan unregistered Pihak Pelapor beserta monitoring populasi.',
                'success_indicator' => 'Pengawasan Pihak Pelapor yang Tepat Sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'REKAN')->first()->id,
            ],
            [
                'name'              => 'Audit kepatuhan tematik atau audit khusus',
                'comment'           => 'Melaksanakan audit kepatuhan tematik atau audit khusus yang massive dan sistemik.',
                'success_indicator' => 'Pengawasan Pihak Pelapor yang Tepat Sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PENJAGA')->first()->id,
            ],
            [
                'name'              => 'Audit kepatuhan tematik atau audit khusus',
                'comment'           => 'Melaksanakan audit kepatuhan tematik atau audit khusus yang massive dan sistemik.',
                'success_indicator' => 'Pengawasan Pihak Pelapor yang Tepat Sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PATUH')->first()->id,
            ],
            [
                'name'              => 'LPP menindaklanjuti rekomendasi PPATK',
                'comment'           => 'Mengharuskan LPP untuk menindaklanjuti rekomendasi PPATK terkait pengenaan sanksi dan pencabutan izin usaha.',
                'success_indicator' => 'Pengawasan Pihak Pelapor yang Tepat Sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PENJAGA')->first()->id,
            ],
            [
                'name'              => 'LPP menindaklanjuti rekomendasi PPATK',
                'comment'           => 'Mengharuskan LPP untuk menindaklanjuti rekomendasi PPATK terkait pengenaan sanksi dan pencabutan izin usaha.',
                'success_indicator' => 'Pengawasan Pihak Pelapor yang Tepat Sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PATUH')->first()->id,
            ],
            [
                'name'              => 'Mengenakan sanksi yang memiliki efek jera bagi pihak pelapor unregistered dan unreporting',
                'comment'           => 'Mengenakan sanksi yang memiliki efek jera bagi pihak pelapor unregistered dan unreporting.',
                'success_indicator' => 'Pengawasan Pihak Pelapor yang Tepat Sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PENJAGA')->first()->id,
            ],
            [
                'name'              => 'Mengenakan sanksi yang memiliki efek jera bagi pihak pelapor unregistered dan unreporting',
                'comment'           => 'Mengenakan sanksi yang memiliki efek jera bagi pihak pelapor unregistered dan unreporting.',
                'success_indicator' => 'Pengawasan Pihak Pelapor yang Tepat Sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PATUH')->first()->id,
            ],
            [
                'name'              => 'Mengembangkan sistem pengawasan pelaporan dan kepatuhan',
                'comment'           => 'Mengembangkan sistem pendukung pengawasan pelaporan dan kepatuhan.',
                'success_indicator' => 'Pengawasan Pihak Pelapor yang Tepat Sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'LOGIS')->first()->id,
            ],
            [
                'name'              => 'Mengembangkan sistem pengawasan pelaporan dan kepatuhan',
                'comment'           => 'Mengembangkan sistem pendukung pengawasan pelaporan dan kepatuhan.',
                'success_indicator' => 'Pengawasan Pihak Pelapor yang Tepat Sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'REKAN')->first()->id,
            ],
            [
                'name'              => 'Mengembangkan sistem pengawasan pelaporan dan kepatuhan',
                'comment'           => 'Mengembangkan sistem pendukung pengawasan pelaporan dan kepatuhan.',
                'success_indicator' => 'Pengawasan Pihak Pelapor yang Tepat Sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PENJAGA')->first()->id,
            ],
            [
                'name'              => 'Mengembangkan sistem pengawasan pelaporan dan kepatuhan',
                'comment'           => 'Mengembangkan sistem pendukung pengawasan pelaporan dan kepatuhan.',
                'success_indicator' => 'Pengawasan Pihak Pelapor yang Tepat Sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PATUH')->first()->id,
            ],
            [
                'name'              => 'Mengenakan sanksi yang memiliki efek jera bagi pihak pelapor yang menyampaikan laporan tidak berkualitas',
                'comment'           => 'Mengenakan sanksi yang memiliki efek jera bagi pihak pelapor yang menyampaikan laporan tidak berkualitas.',
                'success_indicator' => 'Laporan berkualitas yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PENJAGA')->first()->id,
            ],
            [
                'name'              => 'Mengenakan sanksi yang memiliki efek jera bagi pihak pelapor yang menyampaikan laporan tidak berkualitas',
                'comment'           => 'Mengenakan sanksi yang memiliki efek jera bagi pihak pelapor yang menyampaikan laporan tidak berkualitas.',
                'success_indicator' => 'Laporan berkualitas yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PATUH')->first()->id,
            ],
            [
                'name'              => 'Melaksanakan asistensi dan bimtek yang tepat sasaran',
                'comment'           => 'Melaksanakan asistensi dan bimtek yang tepat sasaran (baik objek maupun materinya).',
                'success_indicator' => 'Laporan berkualitas yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PENJAGA')->first()->id,
            ],
            [
                'name'              => 'Melaksanakan asistensi dan bimtek yang tepat sasaran',
                'comment'           => 'Melaksanakan asistensi dan bimtek yang tepat sasaran (baik objek maupun materinya).',
                'success_indicator' => 'Laporan berkualitas yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PATUH')->first()->id,
            ],
            [
                'name'              => 'Segera menetapkan 35 RPerPPATK/RSE',
                'comment'           => 'Segera menetapkan 35 RPerPPATK/RSE mengenai pelaporan.',
                'success_indicator' => 'Laporan berkualitas yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'KREASI')->first()->id,
            ],
            [
                'name'              => 'Penguatan fungsi FIR',
                'comment'           => 'Penguatan fungsi FIR sebagai Rapor Pihak Pelapor.',
                'success_indicator' => 'Laporan berkualitas yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'REKAN')->first()->id,
            ],
            [
                'name'              => 'Penguatan fungsi FIR',
                'comment'           => 'Penguatan fungsi FIR sebagai Rapor Pihak Pelapor.',
                'success_indicator' => 'Laporan berkualitas yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PENJAGA')->first()->id,
            ],
            [
                'name'              => 'Penguatan fungsi FIR',
                'comment'           => 'Penguatan fungsi FIR sebagai Rapor Pihak Pelapor.',
                'success_indicator' => 'Laporan berkualitas yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PATUH')->first()->id,
            ],
            [
                'name'              => 'Membangun aplikasi “Identifikasi Pelaporan yang Berkualitas dan Tidak Berkualitas”',
                'comment'           => 'Membangun aplikasi “Identifikasi Pelaporan yang Berkualitas dan Tidak Berkualitas”',
                'success_indicator' => 'Laporan berkualitas yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'LOGIS')->first()->id,
            ],
            [
                'name'              => 'Membangun aplikasi “Identifikasi Pelaporan yang Berkualitas dan Tidak Berkualitas”',
                'comment'           => 'Pengembangan aplikasi “Identifikasi Pelaporan yang Berkualitas dan Tidak Berkualitas”',
                'success_indicator' => 'Laporan berkualitas yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya basis data')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'REKAN')->first()->id,
            ],

            // SUBJECT DETAIL KE 2
            // =====================
            [
                'name'              => 'Melaksanakan prioritas inquiry',
                'comment'           => 'Melaksanakan prioritas inquiry dengan melakukan pemetaan terhadap inquiry yang belum ditindaklanjuti.',
                'success_indicator' => 'Pola kerja yang memanfaatkan seluruh basis data PPATK',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terlaksananya pola kerja baru')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SIASAT')->first()->id,
            ],
            [
                'name'              => 'Melaksanakan prioritas inquiry',
                'comment'           => 'Melaksanakan prioritas inquiry dengan melakukan pemetaan terhadap inquiry yang belum ditindaklanjuti.',
                'success_indicator' => 'Pola kerja yang memanfaatkan seluruh basis data PPATK',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terlaksananya pola kerja baru')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SIAGA')->first()->id,
            ],
            [
                'name'              => 'Melaksanakan scoring LTKM di goAML',
                'comment'           => 'Melaksanakan scoring LTKM di goAML.',
                'success_indicator' => 'Pola kerja yang memanfaatkan seluruh basis data PPATK',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terlaksananya pola kerja baru')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'LOGIS')->first()->id,
            ],
            [
                'name'              => 'Ditempatkannya pegawai yang memiliki kompetensi sebagai ahli data mining atau data scientist',
                'comment'           => 'Ditempatkannya pegawai yang memiliki kompetensi sebagai ahli data mining atau data scientist pada ASA.',
                'success_indicator' => 'Pola kerja yang memanfaatkan seluruh basis data PPATK',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terlaksananya pola kerja baru')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BERMAKNA')->first()->id,
            ],
            [
                'name'              => 'Restrukturisasi fungsi ASA 1 dan ASA 2',
                'comment'           => 'Restrukturisasi fungsi ASA 1 dan ASA 2.',
                'success_indicator' => 'Pola kerja yang memanfaatkan seluruh basis data PPATK',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terlaksananya pola kerja baru')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BERMAKNA')->first()->id,
            ],
            [
                'name'              => 'Ditempatkannya pegawai yang memiliki kompetensi analisis strategis pada ASA',
                'comment'           => 'Penempatan pegawai yang memiliki kompetensi analisis strategis pada ASA.',
                'success_indicator' => 'Pola kerja yang memanfaatkan seluruh basis data PPATK',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terlaksananya pola kerja baru')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BERMAKNA')->first()->id,
            ],
            [
                'name'              => 'Membentuk Tim Kerja Implementasi Aplikasi Go AML',
                'comment'           => 'Membentuk Tim Kerja Implementasi Aplikasi Go AML.',
                'success_indicator' => 'Sistem informasi yang andal',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terlaksananya pola kerja baru')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'LOGIS')->first()->id,
            ],
            [
                'name'              => 'Implementasi scoring LTKM proaktif di goAML',
                'comment'           => 'Implementasi scoring LTKM proaktif di goAML.',
                'success_indicator' => 'Sistem informasi yang andal',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terlaksananya pola kerja baru')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'LOGIS')->first()->id,
            ],
            [
                'name'              => 'Memperbaiki tampilan field transaction info secara lengkap',
                'comment'           => 'Memperbaiki tampilan field transaction info secara lengkap.',
                'success_indicator' => 'Sistem informasi yang andal',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terlaksananya pola kerja baru')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'LOGIS')->first()->id,
            ],
            [
                'name'              => 'Melakukan finetuning atas konfigurasi perangkat lunak database oleh expert',
                'comment'           => 'Melakukan finetuning atas konfigurasi perangkat lunak database oleh expert.',
                'success_indicator' => 'Sistem informasi yang andal',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terlaksananya pola kerja baru')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'LOGIS')->first()->id,
            ],
            [
                'name'              => 'Otomatisasi scoring prioritas inquiry di goAML',
                'comment'           => 'Otomatisasi scoring prioritas inquiry di goAML.',
                'success_indicator' => 'Sistem informasi yang andal',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terlaksananya pola kerja baru')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'LOGIS')->first()->id,
            ],
            [
                'name'              => 'Otomatisasi proses profiling PEA di goAML',
                'comment'           => 'Otomatisasi proses profiling PEA di goAML.',
                'success_indicator' => 'Sistem informasi yang andal',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terlaksananya pola kerja baru')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'LOGIS')->first()->id,
            ],
            [
                'name'              => 'Menyediakan fitur untuk menghapus data pelaporan',
                'comment'           => 'Menyediakan fitur untuk menghapus data pelaporan yang sudah terkonfirmasi salah dan melakukan rekonsiliasi data dampak atas penghapusan data pelaporan.',
                'success_indicator' => 'Sistem informasi yang andal',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terlaksananya pola kerja baru')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'LOGIS')->first()->id,
            ],
            [
                'name'              => 'Menyediakan fitur penanda (flagging) laporan',
                'comment'           => 'Menyediakan fitur penanda (flagging) laporan yang sudah dilakukan data mining tanpa menjalankan workflow goAML.',
                'success_indicator' => 'Sistem informasi yang andal',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terlaksananya pola kerja baru')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'LOGIS')->first()->id,
            ],

            // SUBJECT DETAIL KE 3
            // =====================
            [
                'name'              => 'Melakukan perubahan bobot penilaian prioritas inquiry',
                'comment'           => 'Melakukan perubahan bobot penilaian prioritas inquiry (amandemen Peraturan PPATK Nomor 10 tahun 2023).',
                'success_indicator' => 'Feedback tindak lanjut atas 100% HA/HP/INF PPATK yang berkelanjutan',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'KREASI')->first()->id,
            ],
            [
                'name'              => 'Implementasi pemenuhan inqury berdasarkan bobot penilaian prioritas inquiry',
                'comment'           => 'Implementasi pemenuhan inqury berdasarkan bobot penilaian prioritas inquiry.',
                'success_indicator' => 'Feedback tindak lanjut atas 100% HA/HP/INF PPATK yang berkelanjutan',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SIAGA')->first()->id,
            ],
            [
                'name'              => 'Memastikan tindak lanjut pemetaan HA/HP berjalan secara efektif',
                'comment'           => 'Memastikan tindak lanjut pemetaan HA/HP berjalan secara efektif.',
                'success_indicator' => 'Feedback tindak lanjut atas 100% HA/HP/INF PPATK yang berkelanjutan',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SALAM')->first()->id,
            ],
            [
                'name'              => 'Mempercepat interconnectivity SISPEKA',
                'comment'           => 'Mempercepat interconnectivity SISPEKA dengan instansi penerima.',
                'success_indicator' => 'Feedback tindak lanjut atas 100% HA/HP/INF PPATK yang berkelanjutan',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'REKAN')->first()->id,
            ],
            [
                'name'              => 'Mempercepat interconnectivity SISPEKA',
                'comment'           => 'Mempercepat interconnectivity SISPEKA dengan instansi penerima.',
                'success_indicator' => 'Feedback tindak lanjut atas 100% HA/HP/INF PPATK yang berkelanjutan',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SALAM')->first()->id,
            ],
            [
                'name'              => 'Mempercepat interconnectivity SISPEKA',
                'comment'           => 'Mempercepat interconnectivity SISPEKA dengan instansi penerima.',
                'success_indicator' => 'Feedback tindak lanjut atas 100% HA/HP/INF PPATK yang berkelanjutan',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'LOGIS')->first()->id,
            ],
            [
                'name'              => 'Melakukan penyampaian informasi khusus kepada BPK RI',
                'comment'           => 'Melakukan penyampaian informasi khusus kepada BPK RI untuk oversight pemanfaatan HA/HP/INF PPATK.',
                'success_indicator' => 'Memanfaatkan peran BPK RI dan Komite TPPU',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SIASAT')->first()->id,
            ],
            [
                'name'              => 'Melakukan penyampaian informasi khusus kepada BPK RI',
                'comment'           => 'Melakukan penyampaian informasi khusus kepada BPK RI untuk oversight pemanfaatan HA/HP/INF PPATK.',
                'success_indicator' => 'Memanfaatkan peran BPK RI dan Komite TPPU',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SIDIK')->first()->id,
            ],
            [
                'name'              => 'Tim kerja Komite TPPU segera melakukan pembahasan secara berkelanjutan mengenai rendahnya jumlah pemanfaatan HA/HP/INF',
                'comment'           => 'Tim kerja Komite TPPU segera melakukan pembahasan secara berkelanjutan mengenai rendahnya jumlah pemanfaatan HA/HP/INF dan menyepakati solusi.',
                'success_indicator' => 'Memanfaatkan peran BPK RI dan Komite TPPU',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SALAM')->first()->id,
            ],
            [
                'name'              => 'Melaksanakan Forum Tim Pelaksana dan Tim Kerja Komite TPPU Dalam Penanganan Kasus Yang Berasal dari HA/HP/INF PPATK',
                'comment'           => 'Melaksanakan Forum Tim Pelaksana dan Tim Kerja Komite TPPU Dalam Penanganan Kasus Yang Berasal dari HA/HP/INF PPATK Yang Sistemik secara berkala.',
                'success_indicator' => 'Komitmen penanganan HA/HP/INF PPATK yang sistemik',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SALAM')->first()->id,
            ],
            [
                'name'              => 'Melaksanakan Forum Tim Pelaksana dan Tim Kerja Komite TPPU Dalam Penanganan Kasus Yang Berasal dari HA/HP/INF PPATK',
                'comment'           => 'Melaksanakan Forum Tim Pelaksana dan Tim Kerja Komite TPPU Dalam Penanganan Kasus Yang Berasal dari HA/HP/INF PPATK Yang Sistemik secara berkala.',
                'success_indicator' => 'Komitmen penanganan HA/HP/INF PPATK yang sistemik',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SIASAT')->first()->id,
            ],
            [
                'name'              => 'Melaksanakan Forum Tim Pelaksana dan Tim Kerja Komite TPPU Dalam Penanganan Kasus Yang Berasal dari HA/HP/INF PPATK',
                'comment'           => 'Melaksanakan Forum Tim Pelaksana dan Tim Kerja Komite TPPU Dalam Penanganan Kasus Yang Berasal dari HA/HP/INF PPATK Yang Sistemik secara berkala.',
                'success_indicator' => 'Komitmen penanganan HA/HP/INF PPATK yang sistemik',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SIDIK')->first()->id,
            ],
            [
                'name'              => 'Melakukan validasi atas kualitas laporan capaian rencana aksi Strategi Nasional TPPU dan TPPT',
                'comment'           => 'Melakukan validasi atas kualitas laporan capaian rencana aksi Strategi Nasional TPPU dan TPPT.',
                'success_indicator' => 'Komitmen penanganan HA/HP/INF PPATK yang sistemik',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SALAM')->first()->id,
            ],
            [
                'name'              => 'Menetapkan dan melaksanakan hasil pemetaan kebutuhan kerjasama domestik dan internasional yang mendukung core ppatk',
                'comment'           => 'Menetapkan dan melaksanakan hasil pemetaan kebutuhan kerjasama domestik dan internasional yang mendukung core ppatk.',
                'success_indicator' => 'Kerja sama domestik dan internasional yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SALAM')->first()->id,
            ],
            [
                'name'              => 'Menetapkan dan melaksanakan hasil pemetaan kebutuhan kerjasama domestik dan internasional yang mendukung core ppatk',
                'comment'           => 'Menetapkan dan melaksanakan hasil pemetaan kebutuhan kerjasama domestik dan internasional yang mendukung core ppatk.',
                'success_indicator' => 'Kerja sama domestik dan internasional yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SERASI')->first()->id,
            ],
            [
                'name'              => 'Melakukan evaluasi kerja sama domestik dan internasional dan ditindaklanjuti dengan pengakhiran atau perpanjangan Nota Kesepahaman',
                'comment'           => 'Melakukan evaluasi kerja sama domestik dan internasional dan ditindaklanjuti dengan pengakhiran atau perpanjangan Nota Kesepahaman.',
                'success_indicator' => 'Kerja sama domestik dan internasional yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SALAM')->first()->id,
            ],
            [
                'name'              => 'Melakukan evaluasi kerja sama domestik dan internasional dan ditindaklanjuti dengan pengakhiran atau perpanjangan Nota Kesepahaman',
                'comment'           => 'Melakukan evaluasi kerja sama domestik dan internasional dan ditindaklanjuti dengan pengakhiran atau perpanjangan Nota Kesepahaman.',
                'success_indicator' => 'Kerja sama domestik dan internasional yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SERASI')->first()->id,
            ],
            [
                'name'              => 'Membangun dan melaksanakan kerja sama yang tepat sasaran dan berdaya guna',
                'comment'           => 'Membangun dan melaksanakan kerja sama yang tepat sasaran dan berdaya guna.',
                'success_indicator' => 'Kerja sama domestik dan internasional yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SALAM')->first()->id,
            ],
            [
                'name'              => 'Membangun dan melaksanakan kerja sama yang tepat sasaran dan berdaya guna',
                'comment'           => 'Membangun dan melaksanakan kerja sama yang tepat sasaran dan berdaya guna.',
                'success_indicator' => 'Kerja sama domestik dan internasional yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SERASI')->first()->id,
            ],
            [
                'name'              => 'Melakukan case work meeting dengan FIU negara lain',
                'comment'           => 'Melakukan case work meeting dengan FIU negara lain.',
                'success_indicator' => 'Kerja sama domestik dan internasional yang tepat sasaran',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Terbangunnya networking')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'SERASI')->first()->id,
            ],

            // SUBJECT DETAIL KE 4
            // =====================
            [
                'name'              => 'Penambahkan fungsi pengaduan masyarakat proaktif pada PBERMITRA',
                'comment'           => 'Penambahkan fungsi pengaduan masyarakat proaktif pada Pusat Pemberdayaan dan Kemitraan APU PPT.',
                'success_indicator' => 'Dumas Proaktif, Strategic Public Relation, dan Media Center APU-PPT Berorientasi Pentahelix Collaboration',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Termanfaatkannya public view')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BERMAKNA')->first()->id,
            ],
            [
                'name'              => 'Penambahkan fungsi pengaduan masyarakat proaktif pada PBERMITRA',
                'comment'           => 'Penambahkan fungsi pengaduan masyarakat proaktif pada Pusat Pemberdayaan dan Kemitraan APU PPT.',
                'success_indicator' => 'Dumas Proaktif, Strategic Public Relation, dan Media Center APU-PPT Berorientasi Pentahelix Collaboration',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Termanfaatkannya public view')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BERMITRA')->first()->id,
            ],
            [
                'name'              => 'Melaksanakan fungsi pengaduan masyarakat proaktif yang didukung dengan tools dan personal yang profesional',
                'comment'           => 'Melaksanakan fungsi pengaduan masyarakat proaktif yang didukung dengan tools dan personal yang profesional.',
                'success_indicator' => 'Dumas Proaktif, Strategic Public Relation, dan Media Center APU-PPT Berorientasi Pentahelix Collaboration',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Termanfaatkannya public view')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BERMAKNA')->first()->id,
            ],
            [
                'name'              => 'Melaksanakan fungsi pengaduan masyarakat proaktif yang didukung dengan tools dan personal yang profesional',
                'comment'           => 'Melaksanakan fungsi pengaduan masyarakat proaktif yang didukung dengan tools dan personal yang profesional.',
                'success_indicator' => 'Dumas Proaktif, Strategic Public Relation, dan Media Center APU-PPT Berorientasi Pentahelix Collaboration',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Termanfaatkannya public view')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BERMITRA')->first()->id,
            ],
            [
                'name'              => 'Melaksanakan fungsi pengaduan masyarakat proaktif yang didukung dengan tools dan personal yang profesional',
                'comment'           => 'Melaksanakan fungsi pengaduan masyarakat proaktif yang didukung dengan tools dan personal yang profesional.',
                'success_indicator' => 'Dumas Proaktif, Strategic Public Relation, dan Media Center APU-PPT Berorientasi Pentahelix Collaboration',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Termanfaatkannya public view')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'LOGIS')->first()->id,
            ],
            [
                'name'              => 'Menetapkan dan melaksanakan strategic public relation APU PPT',
                'comment'           => 'Melaksanakan fungsi pengaduan masyarakat proaktif yang didukung dengan tools dan personal yang profesional.',
                'success_indicator' => 'Dumas Proaktif, Strategic Public Relation, dan Media Center APU-PPT Berorientasi Pentahelix Collaboration',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Termanfaatkannya public view')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BERMITRA')->first()->id,
            ],
            [
                'name'              => 'Menetapkan dan melaksanakan strategic public relation',
                'comment'           => 'Menetapkan dan melaksanakan strategic public relation APU PPT.',
                'success_indicator' => 'Dumas Proaktif, Strategic Public Relation, dan Media Center APU-PPT Berorientasi Pentahelix Collaboration',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Termanfaatkannya public view')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BIRU')->first()->id,
            ],
            [
                'name'              => 'Menetapkan dan melaksanakan fungsi dan infratruktur “War Room J35”',
                'comment'           => 'Menetapkan dan melaksanakan fungsi dan infratruktur “War Room J35”.',
                'success_indicator' => 'Dumas Proaktif, Strategic Public Relation, dan Media Center APU-PPT Berorientasi Pentahelix Collaboration',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Termanfaatkannya public view')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BERMITRA')->first()->id,
            ],
            [
                'name'              => 'Menetapkan dan melaksanakan fungsi dan infratruktur “War Room J35”',
                'comment'           => 'Menetapkan dan melaksanakan fungsi dan infratruktur “War Room J35”.',
                'success_indicator' => 'Dumas Proaktif, Strategic Public Relation, dan Media Center APU-PPT Berorientasi Pentahelix Collaboration',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Termanfaatkannya public view')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BIRU')->first()->id,
            ],

            // SUBJECT DETAIL KE 5
            // =====================
            [
                'name'              => 'Menetapkan dan melaksanakan kebijakan pola karir yang tepat',
                'comment'           => 'Menetapkan dan melaksanakan kebijakan pola karir yang tepat.',
                'success_indicator' => 'Manajemen SDM yang strategik',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BERMAKNA')->first()->id,
            ],
            [
                'name'              => 'Menetapkan dan melaksanakan manajemen kinerja',
                'comment'           => 'Menetapkan dan melaksanakan manajemen kinerja yang selaran rencana strategis PPATK.',
                'success_indicator' => 'Manajemen SDM yang strategik',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BERMAKNA')->first()->id,
            ],
            [
                'name'              => 'Menetapkan dan melaksanakan manajemen kinerja',
                'comment'           => 'Menetapkan dan melaksanakan manajemen kinerja yang selaran rencana strategis PPATK.',
                'success_indicator' => 'Manajemen SDM yang strategik',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BINCANG')->first()->id,
            ],
            [
                'name'              => 'Melakukan pemetaan kebutuhan personil dan pemberdayaan 100% human capital',
                'comment'           => 'Melakukan pemetaan kebutuhan personil dan pemberdayaan 100% human capital.',
                'success_indicator' => 'Manajemen SDM yang strategik',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BERMAKNA')->first()->id,
            ],
            [
                'name'              => 'Melaksanakan pelayanan prima terkait manajemen SDM',
                'comment'           => 'Melaksanakan pelayanan prima terkait manajemen SDM.',
                'success_indicator' => 'Manajemen SDM yang strategik',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BERMAKNA')->first()->id,
            ],
            [
                'name'              => 'Implementasi building management',
                'comment'           => 'Implementasi building management.',
                'success_indicator' => 'Sarana dan prasaranan yang tepat guna dan pelayanan prima',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BIRU')->first()->id,
            ],
            [
                'name'              => 'Implementasi hasil assessment Mechanical Electrical Plumbing yang antisipatif',
                'comment'           => 'Implementasi hasil assessment Mechanical Electrical Plumbing yang antisipatif.',
                'success_indicator' => 'Sarana dan prasaranan yang tepat guna dan pelayanan prima',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BIRU')->first()->id,
            ],
            [
                'name'              => 'Implementasi assessment dan rekomendasi keamanan akses gedung PPATK',
                'comment'           => 'Implementasi assessment dan rekomendasi keamanan akses gedung PPATK.',
                'success_indicator' => 'Sarana dan prasaranan yang tepat guna dan pelayanan prima',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BIRU')->first()->id,
            ],
            [
                'name'              => 'Klinik pratama melaksanakan standar operasional berbasis layanan prima',
                'comment'           => 'Klinik pratama melaksanakan standar operasional berbasis layanan prima.',
                'success_indicator' => 'Sarana dan prasaranan yang tepat guna dan pelayanan prima',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BERMAKNA')->first()->id,
            ],
            [
                'name'              => 'Revitalisasi dan memanfaatkan gedung ciloto untuk kegiatan arsip, pelatihan, rapat konsinyering',
                'comment'           => 'Revitalisasi dan memanfaatkan gedung ciloto untuk kegiatan arsip, pelatihan, rapat konsinyering.',
                'success_indicator' => 'Sarana dan prasaranan yang tepat guna dan pelayanan prima',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PATIH')->first()->id,
            ],
            [
                'name'              => 'Revitalisasi dan memanfaatkan gedung ciloto untuk kegiatan arsip, pelatihan, rapat konsinyering',
                'comment'           => 'Revitalisasi dan memanfaatkan gedung ciloto untuk kegiatan arsip, pelatihan, rapat konsinyering.',
                'success_indicator' => 'Sarana dan prasaranan yang tepat guna dan pelayanan prima',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BIRU')->first()->id,
            ],
            [
                'name'              => 'Mengimplementasikan manajemen risiko (termasuk BCMS)',
                'comment'           => 'Mengimplementasikan manajemen risiko (termasuk BCMS) yang berhasil guna.',
                'success_indicator' => 'Tata laksana organisasi yang agile',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BERMAKNA')->first()->id,
            ],
            [
                'name'              => 'Melakukan evaluasi dan restrukturisasi fungsi',
                'comment'           => 'Melakukan evaluasi dan restrukturisasi fungsi.',
                'success_indicator' => 'Tata laksana organisasi yang agile',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BERMAKNA')->first()->id,
            ],
            [
                'name'              => 'Melakukan integrasi aplikasi manajemen internal dan core',
                'comment'           => 'Melakukan integrasi aplikasi manajemen internal dan core.',
                'success_indicator' => 'Tata laksana organisasi yang agile',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BERMAKNA')->first()->id,
            ],
            [
                'name'              => 'Melakukan integrasi aplikasi manajemen internal dan core',
                'comment'           => 'Melakukan integrasi aplikasi manajemen internal dan core.',
                'success_indicator' => 'Tata laksana organisasi yang agile',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'LOGIS')->first()->id,
            ],
            [
                'name'              => 'Jabatan eselon 1 segera diisi',
                'comment'           => 'Jabatan eselon 1 segera diisi.',
                'success_indicator' => 'Tata laksana organisasi yang agile',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BERMAKNA')->first()->id,
            ],
            [
                'name'              => 'Membeli dan memelihara perangkat laptop/PC ASA dan Pengasuh',
                'comment'           => 'Membeli dan memelihara perangkat laptop/PC ASA dan Pengasuh.',
                'success_indicator' => 'Infrastruktur TI yang andal',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BIRU')->first()->id,
            ],
            [
                'name'              => 'Membeli dan memelihara perangkat laptop/PC ASA dan Pengasuh',
                'comment'           => 'Membeli dan memelihara perangkat laptop/PC ASA dan Pengasuh.',
                'success_indicator' => 'Infrastruktur TI yang andal',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BIRU')->first()->id,
            ],
            [
                'name'              => 'Menyempurnakan Go AML dan mengembangkan aplikasi pendamping Go AML',
                'comment'           => 'Menyempurnakan Go AML dan mengembangkan aplikasi pendamping Go AML.',
                'success_indicator' => 'Infrastruktur TI yang andal',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'LOGIS')->first()->id,
            ],
            [
                'name'              => 'Menyediakan personil yang memiliki kompetensi business analyst di unit kerja',
                'comment'           => 'Menyediakan personil yang memiliki kompetensi business analyst di unit kerja.',
                'success_indicator' => 'Infrastruktur TI yang andal',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BERMAKNA')->first()->id,
            ],
            [
                'name'              => 'Membeli perangkat security jaringan PPATK yang dapat memonitor 24 jam dan perangkat untuk AI (GPU)',
                'comment'           => 'Membeli perangkat security jaringan PPATK yang dapat memonitor 24 jam dan perangkat untuk AI (GPU).',
                'success_indicator' => 'Infrastruktur TI yang andal',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'LOGIS')->first()->id,
            ],
            [
                'name'              => 'Melaksanakan pengembangan kompetensi tepat sasaran',
                'comment'           => 'Melaksanakan pengembangan kompetensi tepat sasaran.',
                'success_indicator' => 'Infrastruktur TI yang andal',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BERMAKNA')->first()->id,
            ],
            [
                'name'              => 'Menetapkan standarisasi keamanan perangkat TI untuk pelaporan di PP dan memastikan diimplementasikan oleh PP',
                'comment'           => 'Menetapkan standarisasi keamanan perangkat TI untuk pelaporan di PP dan memastikan diimplementasikan oleh PP.',
                'success_indicator' => 'Infrastruktur TI yang andal',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'LOGIS')->first()->id,
            ],
            [
                'name'              => 'Melibatkan Unit Kerja pada setiap penyusunan kebijakan anggaran',
                'comment'           => 'Melibatkan Unit Kerja pada setiap penyusunan kebijakan anggaran.',
                'success_indicator' => 'Anggaran yang fleksibel',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BINCANG')->first()->id,
            ],
            [
                'name'              => 'Mengajukan dispensasi pelaksanaan anggaran ke Kementerian Keuangan',
                'comment'           => 'Mengajukan dispensasi pelaksanaan anggaran ke Kementerian Keuangan apabila dibutuhkan core PPATK.',
                'success_indicator' => 'Anggaran yang fleksibel',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BINCANG')->first()->id,
            ],
            [
                'name'              => 'Menugaskan Inspektorat melakukan audit kinerja Bagian TU Kedeputian',
                'comment'           => 'Menugaskan Inspektorat melakukan audit kinerja Bagian TU Kedeputian.',
                'success_indicator' => 'Anggaran yang fleksibel',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PEKA')->first()->id,
            ],
            [
                'name'              => 'Membuat sistem monitoring tagihan',
                'comment'           => 'Membuat sistem monitoring tagihan yang dapat diakses seluruh pegawai sesuai kebijakan TI.',
                'success_indicator' => 'Anggaran yang fleksibel',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BINCANG')->first()->id,
            ],
            [
                'name'              => 'Membuat sistem monitoring tagihan',
                'comment'           => 'Membuat sistem monitoring tagihan yang dapat diakses seluruh pegawai sesuai kebijakan TI.',
                'success_indicator' => 'Anggaran yang fleksibel',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'LOGIS')->first()->id,
            ],
            [
                'name'              => 'Menetapkan BPP',
                'comment'           => 'Menetapkan BPP (Bendahara Pengeluaran Pembantu).',
                'success_indicator' => 'Anggaran yang fleksibel',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BINCANG')->first()->id,
            ],
            [
                'name'              => 'Inspektur bertanggung jawab untuk memastikan tingkat pemahaman auditor atas proses bisnis PPATK',
                'comment'           => 'Inspektur bertanggung jawab untuk memastikan tingkat pemahaman auditor atas proses bisnis PPATK.',
                'success_indicator' => 'Pengawasan internal yang tegas dan solutif',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'BINCANG')->first()->id,
            ],
            [
                'name'              => 'Melakukan pengawasan intern terhadap capaian quick win Rapat Kerja 2023',
                'comment'           => 'Melakukan pengawasan intern terhadap capaian quick win Rapat Kerja 2023 sesuai indikator capaian secara berkala.',
                'success_indicator' => 'Pengawasan internal yang tegas dan solutif',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PEKA')->first()->id,
            ],
            [
                'name'              => 'Melaksanakan probity audit berbasis risiko',
                'comment'           => 'Melaksanakan probity audit berbasis risiko.',
                'success_indicator' => 'Pengawasan internal yang tegas dan solutif',
                'start'             => '2023-09-25 00:00:00.000',
                'end'               => '2024-09-25 00:00:00.000',
                'subject_detail_id' => SubjectDetail::where('name', 'Tersedianya human capital, sarana dan prasarana, kelembagaan, informasi teknogi, dan pengawasan internal')->first()->id,
                'jabatan_id'        => Jabatan::where('name', 'PEKA')->first()->id,
            ],
        ];

        foreach ($actions as $action) {
            Action::create([
                'name'              => $action['name'],
                'comment'           => $action['comment'],
                'success_indicator' => $action['success_indicator'],
                'start'             => $action['start'],
                'end'               => $action['end'],
                'subject_detail_id' => $action['subject_detail_id'],
                'jabatan_id'        => $action['jabatan_id'],
            ]);
        }
    }
}
